name: Deployment
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx ng build --base-href=/Japan-Jegyzetek/
      - name: Setting up git email
        run: git config --global user.email "racz1666@gmail.com"
      - name: Setting up git user name
        run: git config --global user.name "racz16"
      - name: Deploy
        run: sudo npx ngh -d dist --no-silent
