name: Deployment
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx ng deploy --base-href=/Japan-Jegyzetek/ --name="racz16" --email=racz1666@gmail.com
